springdoc:
  swagger-ui:
    path: /api-docs

jwt:
  issuer: coin-laundry
  client-secret: secret
  access-token-expiry-date: 1
  refresh-token-expiry-date: 14

oauth:
  kakao:
    client-id: 8c7e17af04af2a1fbb4a8b4d611b313c
    client-secret: SDahbitHfJaWRE22X0Wxm7g3q9GEJUbI
    redirect-uri: http://localhost:3000/api/kakao