spring:
  r2dbc:
    url: r2dbc:${settings.datasource.postgres.url}
    username: ${settings.datasource.postgres.username}
    password: ${settings.datasource.postgres.password}
    pool:
      enabled: true
      max-size: 20
      initial-size: 10
      max-idle-time: 30m
      max-create-connection-time: 10s
      validation-query: SELECT 1
  flyway:
    enabled: true
    url: jdbc:${settings.datasource.postgres.url}
    user: ${settings.datasource.postgres.username}
    password: ${settings.datasource.postgres.password}
    baselineOnMigrate: true

# Environmental Variables
settings:
  datasource:
    postgres:
      url: postgresql://localhost:5432/carry
      username: carry
      password: carry!dev01!#
  external:
    geocoding-api:
      naver:
        base-url: https://naveropenapi.apigw.ntruss.com/map-geocode/v2/geocode
        api-key-id: k61c4xx9ui
        api-key: XPio3f8Es29CpiENQgJw4rGuWpJvprstcxu6lqmT
    reverse-geocoding-api:
      naver:
        base-url: https://naveropenapi.apigw.ntruss.com/map-reversegeocode/v2/gc
        api-key-id: k61c4xx9ui
        api-key: XPio3f8Es29CpiENQgJw4rGuWpJvprstcxu6lqmT
    address-search-api:
      kakao:
        base-url: https://dapi.kakao.com/v2/local/search/address.json
        api-key: 75d70032b85239fd92bd8490927029c2