apiVersion: v1
kind: Service
metadata:
  name: carry-app
  namespace: carry
  labels:
    app.kubernetes.io/name: carry-app
    app.kubernetes.io/part-of: carry-platform
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: carry-app
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
