apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - app/deployment.yaml
  - app/service.yaml
  - app/configmap.yaml
  - app/secret.yaml
  - infra/postgres.yaml
  - infra/kafka.yaml
  - infra/redis.yaml
  - infra/kafka-connect.yaml
  - infra/otel-collector.yaml
  - infra/jaeger.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
