apiVersion: v1
kind: Namespace
metadata:
  name: carry
  labels:
    app.kubernetes.io/part-of: carry-platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: carry-infra
  labels:
    app.kubernetes.io/part-of: carry-platform
